'use client'
import { RecoilRoot } from 'recoil'
import './globals.css'
// export const metadata = {
//   title: 'Instagram',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <RecoilRoot>
      <body className='bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>{children}</body>
      </RecoilRoot>
    
    </html>
  )
}
